version: "3.8"

services:
  # db service removed as we are connecting to external Cloud SQL

  backend:
    build:
      context: ./interpreter-backend
      dockerfile: Dockerfile
    container_name: interpreter_backend
    # depends_on removed as db service is gone
    environment:
      # Variables from env_file will be loaded here automatically
      PORT: 8080 # Make sure this matches the EXPOSE in backend Dockerfile
      # Add any other necessary backend environment variables here (non-secret)
      JWT_ISSUER: "interpreter-backend-issuer" # Example non-secret
    env_file:
      # Load secrets from this file (relative to docker-compose.yml)
      - ./interpreter-backend/.env
    ports:
      - "8080:8080"
    volumes:
      # Mount code for development (optional, remove for production builds)
      - ./interpreter-backend:/app
      # Avoid mounting node_modules from host
      - /app/node_modules
      - /app/dist # Avoid mounting build output if already built in image
    networks:
      - interpreter_network
    # Generate client, push schema to DB, and then start the application
    command: sh -c "npx prisma generate && npx prisma db push --accept-data-loss && node dist/index.js"

  frontend:
    build:
      context: ./interpreter-frontend
      dockerfile: Dockerfile
      # Pass build args for frontend to know backend host
      args:
        # Use the host-accessible URL for build-time injection
        VITE_APP_BACKEND_URL: http://localhost:8080
    container_name: interpreter_frontend
    depends_on:
      - backend # Frontend still depends on backend
    ports:
      - "80:80" # Nginx default port
    volumes:
      # Mount code for development (optional, requires Nginx setup for hot-reloading or rebuilds)
      - ./interpreter-frontend:/app
      # Avoid mounting node_modules from host
      - /app/node_modules
      - /app/dist # Avoid mounting build output
    networks:
      - interpreter_network
    # Environment variables for runtime (if needed by entrypoint script, not build time)
    # environment:
    #   VITE_BACKEND_WS_HOST: ws://backend:8080

networks:
  interpreter_network:
    driver: bridge
# postgres_data volume removed as db service is gone
