#!/bin/bash

ENV_FILE=".env"
PROJECT_NAME=$(basename "$(pwd)") # Assumes script is run from interpreter-backend dir
DEFAULT_ISSUER="${PROJECT_NAME:-interpreter-backend}-issuer" # Default issuer

echo "--- Generating JWT Configuration ---"

# Generate a secure random string for JWT_SECRET
JWT_SECRET=$(openssl rand -base64 32)
JWT_ISSUER=$DEFAULT_ISSUER

# Ensure .env file exists
touch "$ENV_FILE"

# Remove existing JWT config lines if they exist
sed -i.bak '/^JWT_SECRET=/d' "$ENV_FILE" 2>/dev/null
sed -i.bak '/^JWT_ISSUER=/d' "$ENV_FILE" 2>/dev/null
sed -i.bak '/^# JWT Configuration/d' "$ENV_FILE" 2>/dev/null # Remove header comment too
rm -f "$ENV_FILE.bak" 2>/dev/null

# Add JWT configuration to .env
# Check if .env ends with a newline, if not, add one
if [ -s "$ENV_FILE" ] && [ "$(tail -c 1 "$ENV_FILE")" != "" ]; then
    echo "" >> "$ENV_FILE"
fi
echo "# JWT Configuration (Generated by generate-jwt-config.sh)" >> "$ENV_FILE"
echo "JWT_SECRET=\"$JWT_SECRET\"" >> "$ENV_FILE"
echo "JWT_ISSUER=\"$JWT_ISSUER\"" >> "$ENV_FILE"

echo ".env file updated with JWT_SECRET and JWT_ISSUER."
echo "JWT_SECRET=[Generated and Saved to .env]"
echo "JWT_ISSUER=$JWT_ISSUER"
echo "IMPORTANT: For production, set JWT_SECRET via Secret Manager/Environment Variable in Cloud Run, not from this file." 